config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users

  get "/home/about" => "homes#about", as: "about"

  resources :books, only: [:new, :index, :show, :edit, :create, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  validates :body,    length: { maximum: 200 }


  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  validates :comment, presence: true, length: { maximum: 140 }
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_one_attached :profile_image
  validates :name, uniqueness: true
  validates :name,    length: { in: 2..20 }
  validates :introduction,    length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end



  def after_sign_out_path_for(resource)
    root_path
  end



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile_image, :introduction])
  end


end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = book.id
    if  @comment.save
      redirect_to book_path(book)
    else
      redirect_to book_path(book)
    end
  end

  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.new
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      @users = User.all
      render :edit
    end

  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_create.html.erb
<h2 class="mt-3">New book</h2>


  <%= form_with model: book do |f| %>

  <div class="form-group">
    <label for="book_title">Title</label>
    <input class="form-control book_title" type="text" name="book[title]" id="book_title">
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <textarea class="form-control book_body" name="book[body]" id="book_body"></textarea>
  </div>
  <div class="form-group">
    <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
  </div>

  <% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">



    <h1>Editing Book</h1>
    <% if @book.errors.any? %>
      <div id="error_explanation">
        <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_with model: @book do |f| %>

      <div class="form-group">
        <label for="inputTitle">Title</label>
        <%= f.text_field :title, autofocus: true, id:"inputTitle", placeholder:"Title", class:"form-control" %>
      </div>
      <div class="form-group">
        <label for="inputBody">Opinion</label>
        <%= f.text_area :body, autofocus: true, id:"inputBody", placeholder:"Body", class:"form-control" %>
      </div>

      <div class="form-group">
        <input type="submit" name="commit" value="Update Book" class="btn btn-success" data-disable-with="Update Book">
      </div>

    <% end %>

    <%= link_to "Show", book_path(@book) %>
    |
    <%= link_to "Back", books_path %>

  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">

  <div id="error_explanation">
    <% if @book.errors.any? %>
      <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="row">
      <div class="col-md-3">
        <%= render 'users/info', user: current_user %>
        <%= render 'books/create', book: @book %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>

        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th></th>
              <th></th>
              <th colspan="5"></th>
            </tr>
          </thead>
          <tbody>
              <% @books.each do |book| %>
                <tr>
                  <td>
                    <%= link_to user_path(book.user) do %>
                      <%= image_tag book.user.get_profile_image(100,100) %>
                    <% end %>
                    </td>
                  <td><%= link_to book.title, book_path(book.id) %></td>
                  <td><%= book.body %></td>
                  <td>
                    <% if book.favorited_by?(current_user) %>
                      <p class="text-danger">
                        <%= link_to book_favorites_path(book),class: "text-danger", method: :delete do %>
                          <i class="fas fa-heart"></i><%= book.favorites.count %>
                        <% end %>
                      </p>
                      <% else %>
                      <p class="text-primary">
                        <%= link_to book_favorites_path(book),class: "text-primary" ,method: :post do %>
                          <i class="fas fa-heart"></i><%= book.favorites.count %>
                        <% end %>
                      </p>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to "#{book.book_comments.count} コメント", book_path(book) %>
                  </td>
                </tr>
              <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">

      <%= render 'users/info', user: @book.user %>

      <h2 class="mt-3">New book</h2>
      <%= form_with url: '/books', method: :post, model: @book do |f| %>
      <div class="form-group">
        <label for="book_title">Title</label>
        <input class="form-control book_title" type="text" name="book[title]" id="book_title">
      </div>
      <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <textarea class="form-control book_body" name="book[body]" id="book_body"></textarea>
      </div>
      <div class="form-group">
        <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
      </div>

      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
  		<h2>Book detail</h2>

      <table class="table">
        <tbody>
              <tr>
                <td>
                  <%= link_to user_path(@book.user) do %>
                    <%= image_tag @book.user.get_profile_image(80,80) %>
                    <br>
                    <%= @book.user.name %>
                  <% end %>
                </td>
                <td><%= link_to @book.title, book_path(@book) %></td>
                <td><%= @book.body %></td>
                <td>
                    <% if @book.favorited_by?(current_user) %>
                      <p class="text-danger">
                        <%= link_to book_favorites_path(@book),class: "text-danger" , method: :delete do %>
                          <i class="fas fa-heart"></i><%= @book.favorites.count %>
                        <% end %>
                      </p>
                      <% else %>
                      <p class="text-primary">
                        <%= link_to book_favorites_path(@book),class: "text-primary" , method: :post do %>
                          <i class="fas fa-heart"></i><%= @book.favorites.count %>
                        <% end %>
                      </p>
                    <% end %>
                </td>
                <td>
                  コメント数：<%= @book.book_comments.count %>
                </td>
                <td>
                  <% if @book.user == current_user %>
                    <%= link_to "Edit", edit_book_path(@book.id) , class:"btn btn-sm btn-success" %>
                  <% end %>
                </td>
                <td>
                  <% if @book.user == current_user %>
                    <%= link_to "Destroy", book_path(@book), method: :delete , class:"btn btn-sm btn-danger", data: {confirm: "本当に削除しますか？"}%>
                  <% end %>
                </td>

              </tr>
        </tbody>
      </table>
    <table>
        <tbody>

    <% @book.book_comments.each do |book_comment| %>
    <tr>
    <td>
    <%= link_to user_path(book_comment.user) do %>
      <%= image_tag book_comment.user.get_profile_image(80,80) %>
      <br>
      <%= book_comment.user.name %>
    <% end %>
    </td>
    <td>
      <%= book_comment.comment %>
      <% if book_comment.user == current_user %>
        <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete , class:"btn btn-sm btn-danger" %>
      <% end %>
      </td>
      </tr>
    <% end %>
        </tbody>
      </table>
    <%= form_with model: [@book, @book_comment] do |f| %>
      <%= f.text_area :comment, rows: '5', cols: "100" %>
      <%= f.submit "送信" %>
    <% end %>
  </div>
  </div>
</div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      <i class="fas fa-book"></i>
      welcome to
      <strong>Bookers</strong>
      !!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>
        welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>  !!

      </h1>
      <p>In  <i class="fas fa-book"></i> <strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">

          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>

        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="fontawesome-i2svg-active fontawesome-i2svg-complete">
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to root_path, class: 'navbar-brand text-light' do %>
              Bookers
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to user_path(current_user), class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i>
                Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path, class: 'nav-link text-light' do %>
                <i class="fas fa-users"></i>
                Users
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to books_path, class: 'nav-link text-light' do %>
                <i class="fas fa-book-open"></i>
                Books
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to "/users/sign_out", method: :delete, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i>
                logout
              <% end %>
            </li>
            <% else %>
             <li class="nav-item">
              <%= link_to root_path, class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i>
                Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to about_path, class: 'nav-link text-light' do %>
                <i class="fas fa-link"></i>
                About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                <i class="fas fa-user-plus"></i>
                sign up
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to "/users/sign_in", class: 'nav-link text-light' do %>
                <i class="fas fa-sign-in-alt"></i>
                login
              <% end %>

            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <p id="notice"></p>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
  	    <div class="row">
    	    <div class="mx-auto">
    		    <p>CopyRight Infratop.inc</p>
    	    </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_info.html.erb
<div>
  <h2>User info</h2>
  <%= image_tag user.get_profile_image(100,100) %>

  <table class="table">
    <tbody><tr></tr>
    <tr>
	    <th>name</th>
	    <th><%= user.name %></th>
    </tr>
    <tr>
	    <th>introduction</th>
	    <th>
	        <%= user.introduction %>
	     </th>
    </tr>
  </tbody></table>


    <p><%= link_to edit_user_path(user) ,class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
    </p>

</div>

app/views/users/edit.html.erb
<% if @user != current_user %>
  <% redirect_to user_path(current_user) %>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">



    <h2>User info</h2>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h3><%= @user.errors.count %>errors prohibited this obj from being saved:</h3>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_with model: @user do |f| %>

      <div class="form-group">
        <label for="inputName">Name</label>
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name", class:"form-control" %>
      </div>
      <div class="form-group">
        <label for="inputImage">Image</label>
        <%= f.file_field :profile_image, placeholder: "Image", accept: "image/*", class:"form-control-file" %>
      </div>
      <div class="form-group">
        <label for="inputIntroduction">Introduction</label>
        <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", class:"form-control" %>
      </div>

      <div class="form-group">
        <input type="submit" name="commit" value="Update User" class="btn btn-success" data-disable-with="Update User">
      </div>

    <% end %>



  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">

      <%= render 'users/info', user: current_user %>
      <%= render 'books/create', book: @book %>
    </div>
      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>

        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td><%= image_tag user.get_profile_image(100,100) %></td>
                  <td><%= user.name %></td>
                  <td><%= link_to "Show",user_path(user) %></td>
                </tr>
              <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
      <%= render 'books/create', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                <%= image_tag book.user.get_profile_image(100,100) %>
                <% end %>
                </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
              <td>
                    <% if book.favorited_by?(current_user) %>
                      <p class="text-danger">
                        <%= link_to book_favorites_path(book),class: "text-danger", method: :delete do %>
                          <i class="fas fa-heart"></i><%= book.favorites.count %>
                        <% end %>
                      </p>
                      <% else %>
                      <p class="text-primary">
                        <%= link_to book_favorites_path(book),class: "text-primary" ,method: :post do %>
                          <i class="fas fa-heart"></i><%= book.favorites.count %>
                        <% end %>
                      </p>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to "#{book.book_comments.count} コメント", book_path(book) %>
                  </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>